import type { Subject } from '@/types';

// ─── Mata Pelajaran TKA ──────────────────────────────────────────────────────
// Sumber: Peraturan BSKAP No. 045/H/AN/2025 & tka.kemendikdasmen.go.id

export const TKA_SUBJECTS: Subject[] = [
  // Wajib
  {
    id: 'tka-bind',
    code: 'BIND',
    name: 'Bahasa Indonesia',
    exam_type: 'TKA',
    category: 'WAJIB',
    description: 'Membaca, memahami, menganalisis, dan mengevaluasi berbagai jenis teks kompleks.',
    icon: '📖',
    color: 'text-emerald-400',
    total_packages: 4,
  },
  {
    id: 'tka-mat',
    code: 'MAT',
    name: 'Matematika',
    exam_type: 'TKA',
    category: 'WAJIB',
    description: 'Penalaran numerik, aljabar, geometri, statistika, dan peluang tingkat lanjut.',
    icon: '∑',
    color: 'text-blue-400',
    total_packages: 4,
  },
  {
    id: 'tka-bing',
    code: 'BING',
    name: 'Bahasa Inggris',
    exam_type: 'TKA',
    category: 'WAJIB',
    description: 'Reading comprehension, grammar, vocabulary, dan analytical writing.',
    icon: '🇬🇧',
    color: 'text-violet-400',
    total_packages: 4,
  },
  // Saintek
  {
    id: 'tka-matl',
    code: 'MATL',
    name: 'Matematika Lanjut',
    exam_type: 'TKA',
    category: 'SAINTEK',
    description: 'Kalkulus diferensial dan integral, transformasi fungsi, dan analisis real.',
    icon: '∫',
    color: 'text-cyan-400',
    total_packages: 3,
  },
  {
    id: 'tka-fis',
    code: 'FIS',
    name: 'Fisika',
    exam_type: 'TKA',
    category: 'SAINTEK',
    description: 'Mekanika, termodinamika, gelombang, listrik-magnet, dan fisika modern.',
    icon: '⚛️',
    color: 'text-yellow-400',
    total_packages: 3,
  },
  {
    id: 'tka-kim',
    code: 'KIM',
    name: 'Kimia',
    exam_type: 'TKA',
    category: 'SAINTEK',
    description: 'Struktur atom, ikatan kimia, stoikiometri, kimia organik, dan reaksi redoks.',
    icon: '🧪',
    color: 'text-pink-400',
    total_packages: 3,
  },
  {
    id: 'tka-bio',
    code: 'BIO',
    name: 'Biologi',
    exam_type: 'TKA',
    category: 'SAINTEK',
    description: 'Sel, genetika, evolusi, ekologi, anatomi fisiologi manusia, dan bioteknologi.',
    icon: '🧬',
    color: 'text-green-400',
    total_packages: 3,
  },
  {
    id: 'tka-inf',
    code: 'INF',
    name: 'Informatika',
    exam_type: 'TKA',
    category: 'SAINTEK',
    description: 'Algoritma, struktur data, logika komputasi, dan berpikir komputasional.',
    icon: '💻',
    color: 'text-sky-400',
    total_packages: 3,
  },
  // Soshum
  {
    id: 'tka-geo',
    code: 'GEO',
    name: 'Geografi',
    exam_type: 'TKA',
    category: 'SOSHUM',
    description: 'Geografi fisik, geografi manusia, SIG, penginderaan jauh, dan geopolitik.',
    icon: '🌍',
    color: 'text-teal-400',
    total_packages: 3,
  },
  {
    id: 'tka-sej',
    code: 'SEJ',
    name: 'Sejarah',
    exam_type: 'TKA',
    category: 'SOSHUM',
    description: 'Sejarah Indonesia dan dunia dari masa prasejarah hingga kontemporer.',
    icon: '🏛️',
    color: 'text-amber-400',
    total_packages: 3,
  },
  {
    id: 'tka-sos',
    code: 'SOS',
    name: 'Sosiologi',
    exam_type: 'TKA',
    category: 'SOSHUM',
    description: 'Struktur sosial, perubahan sosial, konflik, integrasi, dan penelitian sosial.',
    icon: '👥',
    color: 'text-rose-400',
    total_packages: 3,
  },
  {
    id: 'tka-eko',
    code: 'EKO',
    name: 'Ekonomi',
    exam_type: 'TKA',
    category: 'SOSHUM',
    description: 'Mikro-makroekonomi, akuntansi, manajemen keuangan, dan ekonomi pembangunan.',
    icon: '📊',
    color: 'text-lime-400',
    total_packages: 3,
  },
  {
    id: 'tka-ant',
    code: 'ANT',
    name: 'Antropologi',
    exam_type: 'TKA',
    category: 'SOSHUM',
    description: 'Budaya, tradisi, pranata sosial, relativisme budaya, dan etnografi.',
    icon: '🎭',
    color: 'text-orange-400',
    total_packages: 2,
  },
  // Bahasa & Seni
  {
    id: 'tka-arab',
    code: 'ARAB',
    name: 'Bahasa Arab',
    exam_type: 'TKA',
    category: 'BAHASA_SENI',
    description: 'Membaca, memahami, dan menganalisis teks berbahasa Arab modern.',
    icon: '🌙',
    color: 'text-green-300',
    total_packages: 2,
  },
  {
    id: 'tka-jep',
    code: 'JEP',
    name: 'Bahasa Jepang',
    exam_type: 'TKA',
    category: 'BAHASA_SENI',
    description: 'Membaca hiragana, katakana, kosakata dasar, dan tata bahasa Jepang.',
    icon: '🌸',
    color: 'text-pink-300',
    total_packages: 2,
  },
  {
    id: 'tka-man',
    code: 'MAN',
    name: 'Bahasa Mandarin',
    exam_type: 'TKA',
    category: 'BAHASA_SENI',
    description: 'Membaca hanzi, pinyin, tata bahasa, dan pemahaman bacaan Mandarin.',
    icon: '🐉',
    color: 'text-red-400',
    total_packages: 2,
  },
];

// ─── Komponen UTBK/SNBT ──────────────────────────────────────────────────────
// Sumber: Struktur UTBK 2026 — 150 soal, 195 menit

export const UTBK_SUBJECTS: Subject[] = [
  {
    id: 'utbk-pu',
    code: 'PU',
    name: 'Penalaran Umum',
    exam_type: 'UTBK',
    category: 'TPS',
    description: 'Logika verbal, analisis argumen, inferensi, dan penarikan kesimpulan. (30 soal)',
    icon: '🧠',
    color: 'text-violet-400',
    total_packages: 4,
  },
  {
    id: 'utbk-ppu',
    code: 'PPU',
    name: 'Pengetahuan & Pemahaman Umum',
    exam_type: 'UTBK',
    category: 'TPS',
    description: 'Memahami informasi tertulis, konteks, dan pengetahuan umum. (20 soal)',
    icon: '📚',
    color: 'text-blue-400',
    total_packages: 4,
  },
  {
    id: 'utbk-pbm',
    code: 'PBM',
    name: 'Pemahaman Bacaan & Menulis',
    exam_type: 'UTBK',
    category: 'TPS',
    description: 'Analisis struktur teks, perbaikan kalimat, dan koherensi wacana. (20 soal)',
    icon: '✍️',
    color: 'text-cyan-400',
    total_packages: 4,
  },
  {
    id: 'utbk-pk',
    code: 'PK',
    name: 'Pengetahuan Kuantitatif',
    exam_type: 'UTBK',
    category: 'TPS',
    description: 'Pengolahan data, tabel, grafik, pola bilangan, dan estimasi numerik. (20 soal)',
    icon: '🔢',
    color: 'text-emerald-400',
    total_packages: 4,
  },
  {
    id: 'utbk-lbi',
    code: 'LBI',
    name: 'Literasi Bahasa Indonesia',
    exam_type: 'UTBK',
    category: 'LITERASI',
    description: 'Memahami, menginterpretasi, dan mengevaluasi teks kompleks berbahasa Indonesia. (30 soal)',
    icon: '📖',
    color: 'text-rose-400',
    total_packages: 4,
  },
  {
    id: 'utbk-lbe',
    code: 'LBE',
    name: 'Literasi Bahasa Inggris',
    exam_type: 'UTBK',
    category: 'LITERASI',
    description: 'Reading comprehension, inference, dan critical analysis dalam Bahasa Inggris. (20 soal)',
    icon: '🌐',
    color: 'text-amber-400',
    total_packages: 4,
  },
  {
    id: 'utbk-pm',
    code: 'PM',
    name: 'Penalaran Matematika',
    exam_type: 'UTBK',
    category: 'LITERASI',
    description: 'Penerapan konsep matematika untuk memecahkan masalah kontekstual. (20 soal)',
    icon: '📐',
    color: 'text-sky-400',
    total_packages: 4,
  },
];

// ─── Konfigurasi Aplikasi ─────────────────────────────────────────────────────

export const APP_CONFIG = {
  name: 'Artemis',
  tagline: 'Kuasai TKA & UTBK — Raih PTN Impianmu',
  description: 'Platform latihan soal TKA dan UTBK/SNBT berbasis simulasi cerdas untuk siswa SMA seluruh Indonesia.',
  version: '1.0.0',
  contact_email: 'hello@artemis.id',
} as const;

export const EXAM_CONFIG = {
  TKA: {
    wajib_subjects: 3,
    pilihan_subjects: 2,         // pilih 2 dari 19
    question_types: ['PGS', 'MCMA', 'KATEGORI'] as const,
    disclaimer: 'Sistem penilaian ini adalah simulasi edukatif dan bukan representasi skor resmi TKA.',
  },
  UTBK: {
    total_questions: 150,
    duration_minutes: 195,
    scoring_system: 'IRT',       // Item Response Theory
    no_negative_marking: true,
    disclaimer: 'Sistem penilaian menggunakan simulasi IRT dan bukan nilai UTBK resmi.',
  },
} as const;

export const SCORE_BANDS = [
  { min: 90, label: 'Sangat Unggul',  color: 'text-emerald-400', description: 'Siap menembus PTN terbaik!' },
  { min: 75, label: 'Unggul',         color: 'text-cyan-400',    description: 'Performa sangat baik.' },
  { min: 60, label: 'Cukup',          color: 'text-yellow-400',  description: 'Terus tingkatkan latihanmu.' },
  { min: 45, label: 'Perlu Latihan',  color: 'text-orange-400',  description: 'Perkuat pemahaman konsep dasar.' },
  { min: 0,  label: 'Kritis',         color: 'text-red-400',     description: 'Mulai dari materi fundamental.' },
] as const;
